/* EVENTS */
export const GET_COMPANY_ATTRIBUTES = 'GET_COMPANY_ATTRIBUTES';
export const GET_COMPANY_ATTRIBUTES_SUCCESS = 'GET_COMPANY_ATTRIBUTES_SUCCESS';
export const GET_COMPANY_ATTRIBUTES_FAIL = 'GET_COMPANY_ATTRIBUTES_FAIL';
